### ISSUE TITLE
Can I subclass ScrollViewController?

### ISSUE THREAD

**Issue by Sweeper777** [darrarski/ScrollViewController#2]
I want to create a VC that has the functionality of `ScrollViewController`, but also some of my custom code, like `@IBAction`s for bar button items etc. Do you plan on making the class subclass-able ?

**Comment by darrarski** [comment]
In theory, you can subclass, but I discourage you to do it. Subclassing is in most cases not a good way to implement generalisation. 

You can embed `ScrollViewController` as a child of your own custom view controller to achieve better separation. On the other side, `ScrollViewController` has very simple implementation (it's just to show how to use `ScrollViewKeyboardAvoider` with `KeyboardFrameChangeListener`), that you can reproduce on your own without need to subclassing.
